In [1]:
import pandas as pd
import numpy as np

In [2]:
nota_pratos = pd.read_csv('Cuisine_rating.csv')

In [3]:
nota_pratos.head()

,User ID,Area code,Location,Gender,YOB,Marital Status,Activity,Budget,Cuisines,Alcohol,Smoker,Food Rating,Service Rating,Overall Rating,Often A S
0,1,153,"Upper East Side,NY",Female,2006,Single,Professional,3,Japanese,Never,Never,5,4,4.5,No
1,2,123,"St. George,NY",Female,1991,Married,Student,3,Indian,Never,Socially,1,1,1.0,No
2,3,122,"Upper West Side,NY",Male,1977,Single,Student,5,Seafood,Often,Often,5,5,5.0,Yes
3,4,153,"Upper East Side,NY",Female,1956,Married,Professional,5,Japanese,Never,Socially,3,1,2.0,No
4,5,129,"Central Park,NY",Male,1997,Single,Student,4,Filipino,Socially,Never,2,4,3.0,No

In [6]:
nota_pratos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   User ID         200 non-null    int64
 1   Area code       200 non-null    int64
 2   Location        200 non-null    object
 3   Gender          200 non-null    object
 4   YOB             200 non-null    int64
 5   Marital Status  200 non-null    object
 6   Activity        200 non-null    object
 7   Budget          200 non-null    int64
 8   Cuisines        200 non-null    object
 9   Alcohol         200 non-null    object
 10  Smoker          200 non-null    object
 11  Food Rating     200 non-null    int64
 12  Service Rating  200 non-null    int64
 13  Overall Rating  200 non-null    float64
 14  Often A S       200 non-null    object
dtypes: float64(1), int64(6), object(8)
memory usage: 23.6+ KB

In [7]:
nota_pratos['Location']

0      Upper East Side,NY
1           St. George,NY
2      Upper West Side,NY
3      Upper East Side,NY
4         Central Park,NY
              ...
195         St. George,NY
196    Upper West Side,NY
197         St. George,NY
198         St. George,NY
199    Upper East Side,NY
Name: Location, Length: 200, dtype: object

In [9]:
nota_pratos['Location'].value_counts()

Location
St. George,NY         46
Upper East Side,NY    30
Riverdale,NY          28
Central Park,NY       24
China Town, NY        22
Market City, NY       20
Upper West Side,NY    18
Central Park,ny        8
Market City, MY        2
Cedar Hill, NY         2
Name: count, dtype: int64

In [10]:
nota_pratos[nota_pratos['Overall Rating'] == 5.0]

,User ID,Area code,Location,Gender,YOB,Marital Status,Activity,Budget,Cuisines,Alcohol,Smoker,Food Rating,Service Rating,Overall Rating,Often A S
2,3,122,"Upper West Side,NY",Male,1977,Single,Student,5,Seafood,Often,Often,5,5,5.0,Yes
12,13,123,"St. George,NY",Female,2006,Single,Professional,5,Chinese,Socially,Never,5,5,5.0,No
23,24,154,"Market City, NY",Male,1974,Divorced,Professional,1,Seafood,Socially,Often,5,5,5.0,No
34,35,129,"Central Park,NY",Male,2001,Divorced,Student,1,Japanese,Socially,Often,5,5,5.0,No
41,42,154,"Market City, NY",Female,1967,Single,Student,5,Filipino,Often,Socially,5,5,5.0,No
50,51,107,"Riverdale,NY",Female,2007,Single,Student,4,Japanese,Often,Often,5,5,5.0,Yes
56,57,123,"St. George,NY",Female,1981,Divorced,Student,2,Italian,Socially,Often,5,5,5.0,No
61,62,122,"Upper West Side,NY",Female,1955,Divorced,Professional,4,Japanese,Never,Often,5,5,5.0,No
62,63,123,"St. George,NY",Male,2002,Single,Student,4,Japanese,Never,Often,5,5,5.0,No
64,65,129,"Central Park,NY",Female,1996,Single,Student,4,Italian,Never,Never,5,5,5.0,No
78,79,111,"China Town, NY",Male,1965,Married,Professional,3,Seafood,Often,Often,5,5,5.0,Yes
84,85,153,"Upper East Side,NY",Female,1978,Divorced,Student,4,Chinese,Often,Often,5,5,5.0,Yes
87,88,129,"Central Park,NY",Female,2007,Single,Professional,5,French,Often,Often,5,5,5.0,Yes
88,89,122,"Upper West Side,NY",Female,2003,Married,Professional,4,French,Often,Often,5,5,5.0,Yes
89,90,123,"St. George,NY",Male,1988,Divorced,Professional,3,Indian,Often,Often,5,5,5.0,Yes
92,93,123,"St. George,NY",Male,2000,Single,Professional,5,French,Never,Often,5,5,5.0,No
123,124,113,"Market City, NY",Male,1974,Divorced,Professional,1,Seafood,Socially,Often,5,5,5.0,No
141,142,162,"Market City, NY",Female,1967,Single,Student,5,Filipino,Often,Socially,5,5,5.0,No
150,151,185,"Riverdale,NY",Female,2007,Single,Student,4,Japanese,Often,Often,5,5,5.0,Yes
156,157,176,"St. George,NY",Female,1981,Divorced,Student,2,Italian,Socially,Often,5,5,5.0,No
161,162,125,"Upper West Side,NY",Female,1955,Divorced,Professional,4,Japanese,Never,Often,5,5,5.0,No
162,163,158,"St. George,NY",Male,2002,Single,Student,4,Japanese,Never,Often,5,5,5.0,No
164,165,176,"Central Park,NY",Female,1996,Single,Student,4,Italian,Never,Never,5,5,5.0,No
178,179,149,"China Town, NY",Male,1965,Married,Professional,3,Seafood,Often,Often,5,5,5.0,Yes
184,185,158,"Upper East Side,NY",Female,1978,Divorced,Student,4,Chinese,Often,Often,5,5,5.0,Yes
187,188,137,"Central Park,NY",Female,2007,Single,Professional,5,French,Often,Often,5,5,5.0,Yes
188,189,154,"Upper West Side,NY",Female,2003,Married,Professional,4,French,Often,Often,5,5,5.0,Yes
189,190,167,"St. George,NY",Male,1988,Divorced,Professional,3,Indian,Often,Often,5,5,5.0,Yes
192,193,105,"St. George,NY",Male,2000,Single,Professional,5,French,Never,Often,5,5,5.0,No

In [11]:
nota_pratos['Food Rating'].value_counts()

Food Rating
5    53
3    46
2    35
4    35
1    31
Name: count, dtype: int64

In [13]:
nota_pratos[nota_pratos['Overall Rating'] == 5.0]['Budget'].mean()

3.689655172413793